// Front-End Engineering Foundations — course definition.
// JS-deep, TS-deep, React-deep, Next.js-light foundations for engineers who've
// shipped some React but never went under the hood. Built for the kinds of
// "explain this in 60 seconds" questions that separate juniors from mid/senior
// front-end engineers — useful in interviews, design reviews, and on-call alike.

import type { Module } from "./ai";

export const COURSE_META = {
  id: "frontend" as const,
  slug: "frontend",
  name: "Front-End Engineering Foundations",
  shortName: "FE Foundations",
  tagline: "From basic React to engineer-ready front-end",
  description:
    "Deep front-end fundamentals: JavaScript internals, TypeScript for React engineers, the React rendering model, hooks and state, Next.js, performance, and accessibility. Each idea ends in a checkpoint that gates progress until you can explain it cold.",
  icon: "🎨",
  color: "from-cyan-500 to-sky-500",
  accent: "cyan",
  status: "available" as const,
  language: "JavaScript / TypeScript",
};

// Phase list — all 10 phases (0–9) are shipped and populated. The landing
// page (modulesByPhase in app/courses/frontend/page.tsx) derives its phase
// sections from these names + colors, so this stays the single source of
// truth for phase metadata.
export const PHASES = [
  { number: 0, name: "Orientation", color: "from-slate-500 to-slate-400" },
  { number: 1, name: "JavaScript You Can Defend", color: "from-rose-500 to-orange-500" },
  { number: 2, name: "TypeScript for React Engineers", color: "from-amber-500 to-yellow-500" },
  { number: 3, name: "React Mental Model", color: "from-emerald-500 to-green-500" },
  { number: 4, name: "Hooks in Depth", color: "from-teal-500 to-cyan-500" },
  { number: 5, name: "State, Forms & Data", color: "from-sky-500 to-blue-500" },
  { number: 6, name: "Advanced React Patterns", color: "from-indigo-500 to-purple-500" },
  { number: 7, name: "Next.js (App Router) Essentials", color: "from-violet-500 to-fuchsia-500" },
  { number: 8, name: "Performance, A11y & DX", color: "from-fuchsia-500 to-pink-500" },
  { number: 9, name: "Interview Closers", color: "from-pink-500 to-rose-500" },
];

export const MODULES: Module[] = [
  // Phase 0 · Orientation
  { slug: "welcome", number: 0, phase: "Orientation", phaseNumber: 0, title: "Welcome — what this course is (and isn't)", subtitle: "How the course works, who it's for, and how to use checkpoints under interview pressure", duration: "~5 min", project: "No project — just read", status: "available" },

  // Phase 1 · JavaScript You Can Defend
  { slug: "values-references", number: 1, phase: "JavaScript You Can Defend", phaseNumber: 1, title: "Values, references, and what === actually compares", subtitle: "Primitives vs objects on the stack/heap, why [1] !== [1], and the bugs that follow from spreading the wrong thing", duration: "~1.5–2h", project: "Bug-hunt lab: 12 snippets that look right and aren't — predict, run, explain", status: "available" },
  { slug: "closures-scope", number: 2, phase: "JavaScript You Can Defend", phaseNumber: 1, title: "Closures, scope, and the `var` graveyard", subtitle: "Lexical scope, the closure-in-a-loop classic, why `let` saved us, and the closures hiding in every React hook", duration: "~1.5–2h", project: "Counter factory + implement debounce and throttle from scratch", status: "available" },
  { slug: "this-binding", number: 3, phase: "JavaScript You Can Defend", phaseNumber: 1, title: "`this`, binding, and arrow functions", subtitle: "The four rules (default, implicit, explicit, new), why arrow functions don't have `this`, and the .bind() pattern React class components needed", duration: "~1–1.5h", project: "Rewrite 10 snippets predicting `this` — methods, callbacks, event handlers, arrows", status: "available" },
  { slug: "prototypes-classes", number: 4, phase: "JavaScript You Can Defend", phaseNumber: 1, title: "Prototypes, classes, and what `new` actually does", subtitle: "The prototype chain, why `class` is sugar, instanceof under the hood, and why React stopped recommending classes", duration: "~1.5–2h", project: "Implement `new` from scratch + polyfill Object.create + write a prototype-chain visualizer", status: "available" },
  { slug: "event-loop", number: 5, phase: "JavaScript You Can Defend", phaseNumber: 1, title: "The event loop, microtasks, and macrotasks", subtitle: "Call stack, task queue, microtask queue, why Promise.resolve().then runs before setTimeout(0), and why this matters for React batching", duration: "~2–2.5h", project: "Implement a tiny Promise from scratch (states, then, chaining) + predict log order in 15 snippets", status: "available" },
  { slug: "async-patterns", number: 6, phase: "JavaScript You Can Defend", phaseNumber: 1, title: "Promises, async/await, and the patterns interviewers ask about", subtitle: "Promise states, .then vs await, error propagation, Promise.all/race/allSettled, and the AbortController pattern every React app needs", duration: "~2h", project: "Implement Promise.all + Promise.race from scratch + build a cancellable fetch wrapper", status: "available" },
  { slug: "modules-bundlers", number: 7, phase: "JavaScript You Can Defend", phaseNumber: 1, title: "Modules, bundlers, and what ships to the browser", subtitle: "ESM vs CommonJS, why your import * matters, tree-shaking, code-splitting, and reading a webpack/Next.js bundle output", duration: "~1h", project: "Audit a small Next.js bundle: find the heaviest module, justify whether it should be there", status: "available" },
  { slug: "phase-1-revision", number: 8, phase: "JavaScript You Can Defend", phaseNumber: 1, title: "Phase 1 revision notes", subtitle: "Values/refs, closures, `this`, prototypes, the event loop, async, modules — the JS-foundation reference card you can re-read in 15 minutes before the interview", duration: "~15 min", project: "No project — pure revision", status: "available" },

  // Phase 2 · TypeScript for React Engineers
  { slug: "ts-foundations", number: 9, phase: "TypeScript for React Engineers", phaseNumber: 2, title: "TypeScript foundations — structural typing & the type/interface/any/unknown/never set", subtitle: "Why TypeScript catches bugs JS can't, structural vs nominal typing, `type` vs `interface`, and what `any`/`unknown`/`never` each actually mean", duration: "~1.5–2h", project: "Type a small JSON-shaped library API with no implicit `any`, then deliberately add `unknown` and `never` in the right places", status: "available" },
  { slug: "narrowing-and-guards", number: 10, phase: "TypeScript for React Engineers", phaseNumber: 2, title: "Narrowing, discriminated unions, and exhaustiveness", subtitle: "How TS narrows a type inside an `if`, discriminated unions for state machines, custom type guards, and `never` as the exhaustiveness check that catches every new case", duration: "~1.5–2h", project: "Model a `RequestState` discriminated union (idle/loading/success/error), render each branch, and add a `never` exhaustiveness assert", status: "available" },
  { slug: "generics-deep", number: 11, phase: "TypeScript for React Engineers", phaseNumber: 2, title: "Generics — the real mental model", subtitle: "Why generics exist, `<T>` and constraints, default type params, inference, and the patterns React forces (`PropsWithChildren`, generic hooks, the `<T,>` trailing comma trick in TSX)", duration: "~1.5–2h", project: "Write a generic `useFetch<T>` hook that types the response correctly without `any`, plus a generic `<List items renderItem>` component", status: "available" },
  { slug: "utility-types", number: 12, phase: "TypeScript for React Engineers", phaseNumber: 2, title: "Utility types & type-level transformations", subtitle: "`Partial`/`Pick`/`Omit`/`Record`/`ReturnType`, `keyof` and indexed access, mapped types, conditional types with `infer`, and template literal types — how to derive types instead of hand-maintaining duplicates", duration: "~1.5–2h", project: "Derive a `FormValues` type from a `User` with `Pick`/`Omit`, build a `Record<Status, Config>` lookup, and implement your own `MyPartial<T>` mapped type and `MyReturnType<F>` with `infer`", status: "available" },
  { slug: "react-typing", number: 13, phase: "TypeScript for React Engineers", phaseNumber: 2, title: "Typing React — props, children, refs, events, forwardRef", subtitle: "How to type components, `children` correctly, event handlers, refs, `forwardRef`, and the polymorphic `as` prop pattern — the React-TS patterns interviewers ask about", duration: "~2h", project: "Build a `Button` component that's polymorphic (`as=\"a\" | \"button\"`), accepts a ref, and infers element-correct event handlers", status: "available" },
  { slug: "phase-2-revision", number: 14, phase: "TypeScript for React Engineers", phaseNumber: 2, title: "Phase 2 revision notes", subtitle: "Structural typing, narrowing, generics, and the React-specific patterns — your TypeScript-for-React reference card", duration: "~15 min", project: "No project — pure revision", status: "available" },

  // Phase 3 · React Mental Model
  { slug: "how-react-works", number: 15, phase: "React Mental Model", phaseNumber: 3, title: "How React actually works — reconciliation, the virtual DOM, and keys", subtitle: "What `React.createElement` builds, what reconciliation does, why keys matter (and why index-as-key is a trap), and the difference between mounting and updating", duration: "~1.5–2h", project: "Build a tiny render-and-diff toy in 80 lines, then break a reorderable list with `key={index}` and explain the bug", status: "available" },
  { slug: "rendering-rules", number: 16, phase: "React Mental Model", phaseNumber: 3, title: "Rendering rules — when does a component actually re-render?", subtitle: "What triggers a render, why a new object/function prop breaks `memo`, the `useMemo`/`useCallback` mental model, and why most premature memoization makes things worse", duration: "~1.5–2h", project: "Use the React DevTools profiler to find the unnecessary re-renders in a sample tree and fix the three most expensive ones — without overusing memoization", status: "available" },
  { slug: "state-rules", number: 17, phase: "React Mental Model", phaseNumber: 3, title: "State rules — `useState`, immutability, batching, and lifting state up", subtitle: "Why state is a snapshot, the immutable-update rule, the functional updater (`setX(prev => …)`), automatic batching in React 18+, and when to lift vs colocate", duration: "~1.5–2h", project: "Build a counter that increments three times in one handler (predict the result), then rewrite it correctly with the functional updater", status: "available" },
  { slug: "effects-properly", number: 18, phase: "React Mental Model", phaseNumber: 3, title: "`useEffect` properly — lifecycle, deps, cleanup, and what an effect isn't for", subtitle: "Effects as synchronization (not lifecycle), the dependency array as a closure capture, cleanup functions, StrictMode double-fires, and the \"you might not need an effect\" rules", duration: "~2h", project: "Take a useEffect-heavy component and remove the effects that shouldn't exist (derived state, event handlers, init) — keeping only the genuine sync points", status: "available" },
  { slug: "composition-patterns", number: 19, phase: "React Mental Model", phaseNumber: 3, title: "Composition patterns — children, render props, and compound components", subtitle: "How `children` is the most underrated React API, the render-props pattern, compound components (`<Tabs.List><Tabs.Tab/>`), and why composition beats prop-drilling configuration", duration: "~1.5–2h", project: "Build a compound `<Disclosure>` (Disclosure.Button + Disclosure.Panel) with shared state via context — no prop-drilling", status: "available" },
  { slug: "phase-3-revision", number: 20, phase: "React Mental Model", phaseNumber: 3, title: "Phase 3 revision notes", subtitle: "Reconciliation, rendering rules, state, effects, composition — the React-internals reference card", duration: "~15 min", project: "No project — pure revision", status: "available" },

  // Phase 4 · Hooks in Depth
  { slug: "usestate-usereducer", number: 21, phase: "Hooks in Depth", phaseNumber: 4, title: "`useState` internals & `useReducer` — when state gets complex", subtitle: "How `useState` is `useReducer` under the hood, the snapshot-and-queue model, why the functional updater composes, and when to graduate to a reducer for multi-field, interdependent state", duration: "~1.5–2h", project: "Refactor a 6-`useState` form into one `useReducer` with a typed action union — then add an exhaustiveness check so a new action can't be forgotten", status: "available" },
  { slug: "usecontext", number: 22, phase: "Hooks in Depth", phaseNumber: 4, title: "`useContext` — without the provider hell or the re-render storms", subtitle: "What context is (and isn't) for, why every consumer re-renders when the value changes, the new-object-every-render trap, and splitting state/dispatch contexts to keep renders cheap", duration: "~1.5–2h", project: "Build a `ThemeProvider` + `useTheme`, prove the re-render problem with a counter, then fix it by splitting value/dispatch and memoizing the provider value", status: "available" },
  { slug: "useref-imperative", number: 23, phase: "Hooks in Depth", phaseNumber: 4, title: "`useRef` & `useImperativeHandle` — the escape hatch from state", subtitle: "Refs as the box that survives renders without causing them, DOM refs vs instance variables, focus/scroll/measure patterns, and exposing a controlled imperative API with `forwardRef` + `useImperativeHandle`", duration: "~1.5–2h", project: "Build an `<TextInput>` that exposes `focus()` and `clear()` via `useImperativeHandle`, plus a `usePrevious` hook and a render-counter that don't trigger re-renders", status: "available" },
  { slug: "custom-hooks", number: 24, phase: "Hooks in Depth", phaseNumber: 4, title: "Custom hooks — the real unit of reuse in React", subtitle: "Why a custom hook is just a function that calls hooks, extracting stateful logic without changing the tree, composing hooks, return-shape conventions (tuple vs object), and the difference between sharing logic and sharing state", duration: "~1.5–2h", project: "Extract `useToggle`, `useDebouncedValue`, and `useLocalStorage` from inline component logic — then compose them into a single `useSearchBox` hook", status: "available" },
  { slug: "rules-of-hooks", number: 25, phase: "Hooks in Depth", phaseNumber: 4, title: "The rules of hooks — and the linked-list reason they exist", subtitle: "Why hooks must run in the same order every render (the fiber's hook linked-list), why you can't call them in conditions/loops, what actually breaks when you do, and what `eslint-plugin-react-hooks` is really protecting", duration: "~1–1.5h", project: "Deliberately break the rules (conditional hook, hook in a loop) and watch state land on the wrong hook; then write the correct version and explain the bug out loud", status: "available" },
  { slug: "phase-4-revision", number: 26, phase: "Hooks in Depth", phaseNumber: 4, title: "Phase 4 revision notes", subtitle: "`useState`/`useReducer`, `useContext`, refs, custom hooks, and the rules of hooks — the hooks reference card you can re-read in 15 minutes", duration: "~15 min", project: "No project — pure revision", status: "available" },

  // Phase 5 · State, Forms & Data
  { slug: "controlled-uncontrolled", number: 27, phase: "State, Forms & Data", phaseNumber: 5, title: "Controlled vs uncontrolled inputs — the decision interviewers probe", subtitle: "Who owns the input's value (React state vs the DOM), `value` + `onChange` vs `defaultValue` + ref, why a `value` with no `onChange` freezes the field, and when uncontrolled is the right call", duration: "~1.5–2h", project: "Build the same login form twice — once controlled, once uncontrolled with refs — and write down the exact tradeoffs you felt in each", status: "available" },
  { slug: "forms-validation", number: 28, phase: "State, Forms & Data", phaseNumber: 5, title: "Form state & validation — timing, errors, and when to reach for a library", subtitle: "Validation timing (on submit vs on blur vs on change), error-message UX, touched/dirty tracking, why hand-rolled forms rot, and what react-hook-form actually buys you (uncontrolled + subscriptions)", duration: "~2h", project: "Build a sign-up form with on-blur validation and a submit gate, then re-implement it with react-hook-form and compare the re-render counts", status: "available" },
  { slug: "data-fetching", number: 29, phase: "State, Forms & Data", phaseNumber: 5, title: "Data fetching in React — the `useEffect` trap and the race condition", subtitle: "Why `useEffect` + `fetch` is the wrong default, the stale-response race condition and the `ignore`/`AbortController` fix, loading/error/empty as first-class states, and waterfalls vs parallel fetches", duration: "~2h", project: "Write a `useEffect` fetch that has a visible race condition (fast-typing search), then fix it with an ignore flag and an `AbortController`", status: "available" },
  { slug: "server-cache-state", number: 30, phase: "State, Forms & Data", phaseNumber: 5, title: "Server cache is not client state — the React Query mental model", subtitle: "Why server data is a cache (not state you own), staleness/refetching/dedup/invalidation, the `queryKey` model, optimistic updates, and why this category deserves its own tool instead of `useState` + `useEffect`", duration: "~2h", project: "Replace a hand-rolled fetch+cache with TanStack Query: wire `queryKey`s, add an optimistic mutation, and invalidate on success", status: "available" },
  { slug: "global-url-state", number: 31, phase: "State, Forms & Data", phaseNumber: 5, title: "Where state should live — local, lifted, global, and the URL", subtitle: "The decision tree for state location, why most 'global state' is really server cache or URL state, context vs Zustand vs Redux (and when each is overkill), and using the URL as shareable, back-button-friendly state", duration: "~1.5–2h", project: "Move a filter/sort/pagination UI's state into the URL (searchParams), then add a small Zustand store only for the genuinely-global bit — and justify the split", status: "available" },
  { slug: "phase-5-revision", number: 32, phase: "State, Forms & Data", phaseNumber: 5, title: "Phase 5 revision notes", subtitle: "Controlled/uncontrolled, forms & validation, data fetching, server cache, and state location — the data-layer reference card", duration: "~15 min", project: "No project — pure revision", status: "available" },

  // Phase 6 · Advanced React Patterns
  { slug: "memoization-deep", number: 33, phase: "Advanced React Patterns", phaseNumber: 6, title: "Memoization done right — `memo`, `useMemo`, `useCallback`, and when not to", subtitle: "What each one actually memoizes, referential equality and why a fresh object/function prop defeats `memo`, the cost of memoizing, and the senior instinct for when premature memoization makes code slower and harder to read", duration: "~1.5–2h", project: "Profile a laggy list with the React DevTools profiler, fix the real re-render cause with targeted `memo`/`useCallback`, then delete the memoization that was doing nothing — and justify each call", status: "available" },
  { slug: "suspense-concurrent", number: 34, phase: "Advanced React Patterns", phaseNumber: 6, title: "Suspense & concurrent features — `useTransition`, `useDeferredValue`", subtitle: "What Suspense is (a boundary for declaring loading UI), how concurrent rendering lets React interrupt work, `useTransition` for non-blocking updates, `useDeferredValue` for lagging expensive renders, and why these replace manual `isPending` flags", duration: "~2h", project: "Take a filter-a-big-list UI that janks on every keystroke and make it smooth with `useDeferredValue`, then wrap a slow tab switch in `useTransition` so the old UI stays interactive", status: "available" },
  { slug: "error-boundaries", number: 35, phase: "Advanced React Patterns", phaseNumber: 6, title: "Error boundaries — catching render-time failures", subtitle: "Why a thrown error in render unmounts the whole tree, what an error boundary catches (and what it can't — events, async, SSR), the class-component requirement, `getDerivedStateFromError` vs `componentDidCatch`, and granular boundary placement", duration: "~1–1.5h", project: "Build a reusable `<ErrorBoundary fallback>` component, wrap three independent widgets so one crash doesn't blank the page, and add a reset that lets the user recover without a full reload", status: "available" },
  { slug: "portals-refs-advanced", number: 36, phase: "Advanced React Patterns", phaseNumber: 6, title: "Portals & advanced ref patterns — modals, tooltips, and escaping the tree", subtitle: "Why `createPortal` renders outside the DOM hierarchy while keeping React context and event bubbling, the z-index/overflow problems it solves, focus trapping for accessible modals, and ref callbacks/merging for measuring and forwarding", duration: "~1.5–2h", project: "Build an accessible `<Modal>` with `createPortal`, a focus trap, escape-to-close, and a merged ref — then a tooltip that positions against a portaled layer without clipping", status: "available" },
  { slug: "advanced-composition", number: 37, phase: "Advanced React Patterns", phaseNumber: 6, title: "Advanced composition — slots, polymorphism, and the patterns libraries use", subtitle: "How design-system libraries (Radix, Reach) compose: the `asChild`/slot pattern, polymorphic components, controlled/uncontrolled component APIs, headless components, and choosing composition over a sea of boolean props", duration: "~1.5–2h", project: "Build a headless `<Menu>` (trigger + items, keyboard nav, controlled/uncontrolled) with an `asChild` slot so the trigger can be any element — no styling baked in", status: "available" },
  { slug: "phase-6-revision", number: 38, phase: "Advanced React Patterns", phaseNumber: 6, title: "Phase 6 revision notes", subtitle: "Memoization, Suspense & concurrent features, error boundaries, portals & advanced refs, and advanced composition — the advanced-patterns reference card", duration: "~15 min", project: "No project — pure revision", status: "available" },

  // Phase 7 · Next.js (App Router) Essentials
  { slug: "rsc-mental-model", number: 39, phase: "Next.js (App Router) Essentials", phaseNumber: 7, title: "Server Components vs Client Components — the App Router mental model", subtitle: "What runs where and when, why Server Components are the default and never ship JS, the `\"use client\"` boundary and how it cascades, what you can and can't do on each side, and the serialization rule for props crossing the boundary", duration: "~2h", project: "Take a fully-client page and push everything that can be a Server Component server-side, marking only the genuinely-interactive leaves `\"use client\"` — then read the network tab to confirm the JS bundle shrank", status: "available" },
  { slug: "routing-layouts", number: 40, phase: "Next.js (App Router) Essentials", phaseNumber: 7, title: "File-based routing, layouts, and the loading/error conventions", subtitle: "How the `app/` folder maps to routes, nested layouts that persist across navigation, dynamic segments, route groups, and the `loading.tsx`/`error.tsx`/`not-found.tsx` files that wire Suspense and error boundaries for you", duration: "~1.5–2h", project: "Build a nested dashboard route with a persistent sidebar layout, a dynamic `[id]` segment, a `loading.tsx` skeleton, and an `error.tsx` recovery — and explain what persists vs remounts on navigation", status: "available" },
  { slug: "data-loading-server", number: 41, phase: "Next.js (App Router) Essentials", phaseNumber: 7, title: "Data loading on the server — fetching, caching, and revalidation", subtitle: "`async`/`await` directly in Server Components, the extended `fetch` cache and `revalidate`, request memoization vs the data cache, parallel vs sequential server fetches, and how this sidesteps the client race condition class entirely", duration: "~2h", project: "Convert a client `useEffect` data page to a Server Component that fetches directly, set per-fetch `revalidate`, parallelize two independent loads, and add `loading.tsx` streaming — then compare against the old client version", status: "available" },
  { slug: "mutations-actions", number: 42, phase: "Next.js (App Router) Essentials", phaseNumber: 7, title: "Server Actions & mutations — forms without an API layer", subtitle: "What a `\"use server\"` action is, progressive-enhancement forms that work without JS, `revalidatePath`/`revalidateTag` to refresh server data after a write, `useFormStatus`/`useActionState` for pending and error UI, and where actions fit vs a route handler", duration: "~2h", project: "Build an add/edit/delete to-do feature entirely with Server Actions — no fetch, no API routes — with pending state via `useFormStatus`, optimistic UI, and `revalidatePath` after each mutation", status: "available" },
  { slug: "rendering-strategies", number: 43, phase: "Next.js (App Router) Essentials", phaseNumber: 7, title: "Rendering strategies — static, dynamic, streaming, and the edge", subtitle: "Static vs dynamic rendering and what flips a route dynamic, ISR/`revalidate`, streaming SSR with Suspense boundaries, the Node vs Edge runtime tradeoff, and how to read and reason about the Next.js build output", duration: "~1.5–2h", project: "Take a mixed app and classify each route static/dynamic/streamed, force one static page to ISR with `revalidate`, stream a slow section behind Suspense, and read the build output to confirm each route's strategy", status: "available" },
  { slug: "phase-7-revision", number: 44, phase: "Next.js (App Router) Essentials", phaseNumber: 7, title: "Phase 7 revision notes", subtitle: "Server vs Client Components, routing & layouts, server data loading, Server Actions, and rendering strategies — the App Router reference card", duration: "~15 min", project: "No project — pure revision", status: "available" },

  // Phase 8 · Performance, A11y & DX
  { slug: "rendering-performance", number: 45, phase: "Performance, A11y & DX", phaseNumber: 8, title: "Rendering & bundle performance — Core Web Vitals and what actually moves them", subtitle: "LCP/CLS/INP and what each measures, code-splitting and lazy loading, the cost of hydration, image/font optimization, measuring before optimizing, and the difference between a render problem and a network problem", duration: "~2h", project: "Run Lighthouse on a slow page, identify the single biggest Core Web Vital offender, fix it (lazy-load, image optimize, or split a heavy import), and prove the score moved — no shotgun optimization", status: "available" },
  { slug: "accessibility-deep", number: 46, phase: "Performance, A11y & DX", phaseNumber: 8, title: "Accessibility that survives code review — semantics, keyboard, ARIA", subtitle: "Semantic HTML as the foundation (and why a `<div onClick>` fails), keyboard operability and focus management, the first rule of ARIA (don't), labels and names, `aria-live` for dynamic updates, and testing with a keyboard and a screen reader", duration: "~2h", project: "Take an inaccessible custom dropdown built from divs, rebuild it keyboard-operable with correct roles/states and a managed focus order, and verify it with keyboard-only navigation and a screen reader", status: "available" },
  { slug: "forms-a11y-ux", number: 47, phase: "Performance, A11y & DX", phaseNumber: 8, title: "Accessible, usable forms — labels, errors, and announcing failures", subtitle: "Programmatic label association, grouping with `fieldset`/`legend`, `aria-describedby` for hints and errors, announcing validation failures to assistive tech, focus-on-error, and the inline-vs-summary error pattern that real apps use", duration: "~1.5–2h", project: "Make a multi-field sign-up form fully accessible: associated labels, described-by hints, an error summary that moves focus, per-field `aria-invalid`, and announcements that a screen-reader user actually hears", status: "available" },
  { slug: "testing-frontend", number: 48, phase: "Performance, A11y & DX", phaseNumber: 8, title: "Testing front-end like an engineer — what to test and what not to", subtitle: "The testing trophy (static → unit → integration → e2e), why Testing Library tests behavior not implementation, querying by role/label the way a user does, mocking the network not the component, and the tests that give confidence vs the ones that just slow you down", duration: "~2h", project: "Write a behavior-focused Testing Library suite for a form component (happy path, validation error, async submit with a mocked request) querying by accessible role/label — then add one Playwright e2e for the critical flow", status: "available" },
  { slug: "developer-experience", number: 49, phase: "Performance, A11y & DX", phaseNumber: 8, title: "Developer experience — the tooling that keeps a codebase healthy", subtitle: "ESLint and Prettier and why they're different jobs, TypeScript strict mode, pre-commit hooks and CI gates, conventional project structure, and the small DX investments that compound across a team — the stuff you set up on day one", duration: "~1–1.5h", project: "Set up a front-end project's quality gate from scratch: ESLint + Prettier + TS strict + a pre-commit hook running lint/typecheck, and a CI step that blocks a regression — then break a rule and watch the gate catch it", status: "available" },
  { slug: "phase-8-revision", number: 50, phase: "Performance, A11y & DX", phaseNumber: 8, title: "Phase 8 revision notes", subtitle: "Rendering & bundle performance, accessibility, accessible forms, front-end testing, and developer experience — the quality reference card", duration: "~15 min", project: "No project — pure revision", status: "available" },

  // Phase 9 · Interview Closers
  { slug: "system-design-frontend", number: 51, phase: "Interview Closers", phaseNumber: 9, title: "Front-end system design — how to drive the whiteboard", subtitle: "The framework for a front-end design interview: clarify requirements and scope, sketch component architecture and data flow, choose state location and a data-fetching strategy, then talk performance, accessibility, and tradeoffs out loud — using everything from this course", duration: "~2h", project: "Run a full mock: design a typeahead-search-with-results-feed front-end end to end on paper — components, state, fetching, caching, race handling, a11y, and perf — narrating the tradeoffs as you go", status: "available" },
  { slug: "debugging-war-stories", number: 52, phase: "Interview Closers", phaseNumber: 9, title: "Debugging stories — how to talk about a bug you fixed", subtitle: "Why interviewers ask for a hard bug, the structure of a great answer (symptom → investigation → root cause → fix → prevention), turning the course's classic bugs (closure-in-a-loop, stale closure, the fetch race, key-as-index) into crisp STAR-style stories", duration: "~1.5h", project: "Write up three debugging stories from bugs in this course in symptom→investigation→root-cause→fix→prevention form, then rehearse telling each in under two minutes without notes", status: "available" },
  { slug: "rapid-fire-fundamentals", number: 53, phase: "Interview Closers", phaseNumber: 9, title: "Rapid-fire fundamentals — the 60-second answers", subtitle: "The questions that get fired in the first ten minutes — closures, `this`, the event loop, reconciliation, why keys, controlled vs uncontrolled, server cache vs state, Server vs Client Components — each with a tight, confident 60-second answer drawn straight from the course", duration: "~1.5h", project: "Drill the rapid-fire bank out loud against a timer until each answer lands in 60 seconds — record yourself, then cut every answer down to its load-bearing sentence", status: "available" },
  { slug: "coding-challenges", number: 54, phase: "Interview Closers", phaseNumber: 9, title: "Front-end coding challenges — the ones that actually come up", subtitle: "The recurring live-coding asks: implement debounce/throttle, build a custom hook, a small component from scratch (tabs, autocomplete), `Promise.all` from scratch, and how to narrate your approach, edge cases, and tradeoffs while you type", duration: "~2h", project: "Solve five timed challenges from scratch (debounce, `useFetch`, an accessible autocomplete, `Promise.all`, a stopwatch) narrating aloud — then review each for the edge cases an interviewer would probe", status: "available" },
  { slug: "behavioral-and-closing", number: 55, phase: "Interview Closers", phaseNumber: 9, title: "Behavioral answers & closing strong — tradeoffs, disagreement, and questions to ask", subtitle: "The non-coding rounds: STAR-structured behavioral answers, talking about tradeoffs and technical disagreement without sounding rigid, what to do when you don't know something, and the questions that signal seniority when they turn it back to you", duration: "~1.5h", project: "Prepare STAR answers for the five most common behavioral prompts, script how you'd handle a 'you're wrong' moment gracefully, and write the three questions you'll ask the interviewer that show you think like a senior", status: "available" },
  { slug: "phase-9-revision", number: 56, phase: "Interview Closers", phaseNumber: 9, title: "Phase 9 revision notes — and the course finale", subtitle: "Front-end system design, debugging stories, rapid-fire fundamentals, coding challenges, and behavioral closers — the interview-day reference card, plus the map of everything you covered across all nine phases", duration: "~15 min", project: "No project — you're ready", status: "available" },
];

export function getModuleBySlug(slug: string): Module | undefined {
  return MODULES.find((m) => m.slug === slug);
}
